/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

/**
 *
 * @author MIGUE
 */
public class InformesRecepcionista extends javax.swing.JFrame {

    /**
     * Creates new form InformesRecepcionist
     */
    public InformesRecepcionista() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInformesRecepcionista = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonInformesCheckIn = new javax.swing.JButton();
        jButtonInformesCheckOut = new javax.swing.JButton();
        jButtonInformesPension = new javax.swing.JButton();
        jButtonInformesCaja = new javax.swing.JButton();
        jButtonInformesReservasRecep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informes Recepción");

        javax.swing.GroupLayout jPanelInformesRecepcionistaLayout = new javax.swing.GroupLayout(jPanelInformesRecepcionista);
        jPanelInformesRecepcionista.setLayout(jPanelInformesRecepcionistaLayout);
        jPanelInformesRecepcionistaLayout.setHorizontalGroup(
            jPanelInformesRecepcionistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelInformesRecepcionistaLayout.setVerticalGroup(
            jPanelInformesRecepcionistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );

        jPanel2.setLayout(new java.awt.GridLayout());

        jButtonInformesCheckIn.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButtonInformesCheckIn.setText("Check In");
        jPanel2.add(jButtonInformesCheckIn);

        jButtonInformesCheckOut.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButtonInformesCheckOut.setText("Check Out");
        jPanel2.add(jButtonInformesCheckOut);

        jButtonInformesPension.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButtonInformesPension.setText("Pensión");
        jPanel2.add(jButtonInformesPension);

        jButtonInformesCaja.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButtonInformesCaja.setText("Caja");
        jPanel2.add(jButtonInformesCaja);

        jButtonInformesReservasRecep.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButtonInformesReservasRecep.setText("Reservas");
        jPanel2.add(jButtonInformesReservasRecep);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                    .addComponent(jPanelInformesRecepcionista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanelInformesRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformesRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformesRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformesRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformesRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                 new InformesRecepcionista().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonInformesCaja;
    public javax.swing.JButton jButtonInformesCheckIn;
    public javax.swing.JButton jButtonInformesCheckOut;
    public javax.swing.JButton jButtonInformesPension;
    public javax.swing.JButton jButtonInformesReservasRecep;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanelInformesRecepcionista;
    // End of variables declaration//GEN-END:variables
}
