/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Singleton_State;

import Controlador.ControladorAdministrador;
import Controlador.ControladorLimpiadora;
import Controlador.ControladorRecepcionista;
import Vistas.VistaAdministrador;
import Vistas.VistaLimpiadora;
import Vistas.VistaRecepcionista;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JFrame.setDefaultLookAndFeelDecorated;
import javax.swing.JOptionPane;

/**
 *
 * @author Silvia
 */
public class VistaLoggin extends javax.swing.JFrame {

    /**
     * Creates new form VistaLoggin
     */
    public VistaLoggin() {
        setDefaultLookAndFeelDecorated(true);
        initComponents();
        setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelLabels = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        jLabelContrasenya = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Identificación");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(223, 223, 223));
        jPanel1.setPreferredSize(new java.awt.Dimension(252, 310));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_ams.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanelLabels.setBackground(new java.awt.Color(223, 223, 223));
        jPanelLabels.setOpaque(false);

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelUsuario.setText("Usuario:");

        usernameTxt.setMaximumSize(new java.awt.Dimension(199, 20));
        usernameTxt.setMinimumSize(new java.awt.Dimension(199, 20));
        usernameTxt.setPreferredSize(new java.awt.Dimension(199, 20));

        jLabelContrasenya.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelContrasenya.setText("Contraseña:");

        passwordTxt.setMaximumSize(new java.awt.Dimension(199, 20));
        passwordTxt.setMinimumSize(new java.awt.Dimension(199, 20));
        passwordTxt.setPreferredSize(new java.awt.Dimension(199, 20));

        javax.swing.GroupLayout jPanelLabelsLayout = new javax.swing.GroupLayout(jPanelLabels);
        jPanelLabels.setLayout(jPanelLabelsLayout);
        jPanelLabelsLayout.setHorizontalGroup(
            jPanelLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLabelsLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanelLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelUsuario)
                    .addComponent(jLabelContrasenya)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanelLabelsLayout.setVerticalGroup(
            jPanelLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLabelsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUsuario)
                .addGap(15, 15, 15)
                .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabelContrasenya)
                .addGap(15, 15, 15)
                .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnIngresar.setBackground(new java.awt.Color(255, 255, 204));
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/loginuser.png"))); // NOI18N
        btnIngresar.setText("Login");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 255, 204));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        btnCancelar.setText("Exit");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoLogueo.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(255, 310));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelLabels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnIngresar)
                .addGap(19, 19, 19)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jPanelLabels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngresar)
                    .addComponent(btnCancelar)))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        try {
            // TODO add your handling code here:
              doLogin();
        } catch (Exception ex) {
            Logger.getLogger(VistaLoggin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
          doExit();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelContrasenya;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelLabels;
    public javax.swing.JPasswordField passwordTxt;
    public javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables

  //////METODO QUE RECOGE EL NOMBRE DEL USUARIO PARA MOSTRARLO EN EL LOG Y LO VALIDA
    /////AL IGUAL QUE LA CONTRASEÑA
    private void doLogin() throws Exception{
        Login.setUsername(usernameTxt.getText());
        Login.setPassword(new String(passwordTxt.getPassword()));
        
        if (Login.validate()==1)
        {
                VistaLoggin logg = new VistaLoggin();
                VistaAdministrador vista = new VistaAdministrador();
                ControladorAdministrador con = new ControladorAdministrador(logg, vista);
                vista.setVisible(true);
                con.iniciar();
                dispose();
        }
        
        if (Login.validate()==2)
        {
            VistaRecepcionista vistarec= new VistaRecepcionista();
            ControladorRecepcionista contro = new ControladorRecepcionista(vistarec);
            vistarec.setVisible(true);
            contro.iniciar();
            dispose();
        }
        
        if (Login.validate()==3)
        {            
            VistaLimpiadora vistaLimp = new VistaLimpiadora();
            ControladorLimpiadora controLimp = new ControladorLimpiadora(vistaLimp);
            vistaLimp.setVisible(true);
            controLimp.iniciar();
            dispose();
        }
        
        if(Login.validate()!=1 && Login.validate()!=2 && Login.validate()!=3)
        {
            JOptionPane.showMessageDialog(null, "Usuario no encontrado o contraseña no correcta");
        }
    }
    
    /////METODO PARA SALIR DE LA APLICACION
    private void doExit(){
        System.exit(0);
    }


}
